### ISSUE TITLE
Jobs stopping

### ISSUE THREAD

**Issue by thaiat** [menegazzo/tron-ci#2]
Hi,

kudos for your service, it is very helpfull.
I noticed that some of my job stop doing anything. Other are still firing fine.

As there is little log support right now I'm not sure what to do...

Cheers
Avi

**Comment by menegazzo** [comment]
@thaiat , I am planning to review all service, adding support for scheduling by build number and branch name. I will ask you to wait a little longer right now until I'm not able to do it.

Also, you can fork the project and contribute adding the log support ;)

Cheers,
Fabio

**Comment by thaiat** [comment]
@menegazzo unfortunately i'm don't know python...

**Comment by zalew16** [comment]
@zeto87

**Comment by zalew16** [comment]
Question
